name: dhscanner-sast

on:
  push:
    branches:
      - master
jobs:
  run-dhscanner:
    runs-on: ubuntu-latest

    steps:
      - name: clone dhscanner (with submodules)
        run: |
          git clone --recurse-submodules https://github.com/OrenGitHub/dhscanner
          cd dhscanner
          docker compose -f compose.rel.x64.yaml up -d
        env:
          APPROVED_BEARER_TOKEN_0: ${{ secrets.APPROVED_BEARER_TOKEN_0 }}
          APPROVED_URL_0: ${{ secrets.APPROVED_URL_0 }}

      - name: checkout specific tag
        uses: actions/checkout@v4
        with:
          ref: '1.2.1.dhscanner'

      - name: send healthcheck to dhscanner
        run: |
          curl -X GET \
            -H "Authorization: Bearer ${APPROVED_BEARER_TOKEN_0}" \
            -H "Accept: application/json" \
            http://127.0.0.1:443/${APPROVED_URL_0_HEALTHCHECK}
        env:
          APPROVED_BEARER_TOKEN_0: ${{ secrets.APPROVED_BEARER_TOKEN_0 }}
          APPROVED_URL_0_HEALTHCHECK: ${{ secrets.APPROVED_URL_0_HEALTHCHECK }}

      - name: send the whole repo to dhscanner
        run: |
          tar -cz . | curl -v -X POST \
            -H "Authorization: Bearer ${APPROVED_BEARER_TOKEN_0}" \
            -H "Content-Type: application/octet-stream" \
            -H "Ignore-Testing-Code: true" \
            -H "X-Relevant-Facts: tornado.web.RequestHandler" \
            -H "X-Debug-Queryengine: false" \
            --data-binary @- http://127.0.0.1:443/${APPROVED_URL_0} > output.sarif
          cat output.sarif
        env:
          APPROVED_BEARER_TOKEN_0: ${{ secrets.APPROVED_BEARER_TOKEN_0 }}
          APPROVED_URL_0: ${{ secrets.APPROVED_URL_0 }}

      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: output.sarif

      - name: fail workflow if sarif contains findings
        run: |
          if jq '.runs[].results | length > 0' output.sarif | grep -q 'true'; then
            echo "Sarif findings detected, failing the workflow"
            exit 1
          fi
